[tool.poetry]
name = "PriceTrackerFuel"
version = "0.1.0"
description = ""
authors = ["Seu Nome"]

[tool.poetry.dependencies]
python = "^3.10"
django = "^5.0"
requests = "^2.31"
...

[tool.poetry.dev-dependencies]
