services:
  - type: web
    name: pricetrackerfuel
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn myproject.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pricetrackerfuel-db  # Nome do BD que você criará
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: RENDER
        value: "true"

databases:
  - name: pricetrackerfuel-db
    databaseName: pricetrackerfuel
    user: pricetracker_user
    plan: free  # Para MVP